### ISSUE TITLE
tests not passing

### ISSUE THREAD

**Issue by piranna** [enricostara/telegram.link#10]
If you download the code and follow the [instruction to test it](https://github.com/enricostara/telegram.link/#unit-testing) (just exec `npm test`), the tests are failling. Don't know if the library needs some configuration an the readme needs to be updated, or it's a problem in the dependencies... :-/

**Comment by piranna** [comment]
I have review `package.json` both here and at `telegram-mt-node` and have almost all dependencies set at "latest". This is really ugly, and probably the reason why tests are not passing because latest can be able to install backward incompatible changes. Too bad...

**Comment by enricostara** [comment]
Yes, it was time to freeze all the version dependencies. Check out last telegram.link version and let me know if it's ok! (btw, automatic build was passed)
thanks

**Comment by piranna** [comment]
:+1:
