### ISSUE TITLE
Hi, what tools do you use to genereate the api document?

### ISSUE THREAD

**Issue by wanjochan** [enricostara/telegram.link#25]
thank!

**Comment by derhuerst** [comment]
The [`doc` npm script](https://github.com/enricostara/telegram.link/blob/ab6f693/package.json#L52) lets [Gulp](http://gulpjs.com/) run the [`doc` Gulp task](https://github.com/enricostara/telegram.link/blob/4cd0bbe/gulpfile.js#L7-L12), which calls [Docco](http://jashkenas.github.io/docco/) [with all files in `lib/**/*.js`](https://github.com/enricostara/telegram.link/blob/4cd0bbe/gulpfile.js#L9).
