### ISSUE TITLE
can this be used for group moderation?

### ISSUE THREAD

**Issue by dcsan** [enricostara/telegram.link#9]
this looks like an impressive project! 

what is the main goal of the project to differentiate from features in the bot API?
it maybe interesting to prioritize APIs that are not available through the public (and easy to use) bot API? 

I don't have a full list but group/spam management is badly needed within TG. creating groups and managing user add/remove is not there in the bot api. ~= an open source liberbot...

**Comment by enricostara** [comment]
As stated in the _readme_ the project is a porting in node.js of telegram api, therefore it implements (a subset at this moment) of the API and the protocol documented [here](https://core.telegram.org#telegram-api)
